@echo off
echo Activating DMac virtual environment...
call .\dmac_env\Scripts\activate

echo Running WebArena Dashboard...
cd OpenManus-RL\openmanus_rl\agentgym\agentenv-webarena\webarena\scripts

echo Creating sample data directory...
mkdir sample_data 2>nul

echo Running Streamlit dashboard...
streamlit run webarena_dashboard.py

echo Press any key to exit...
pause > nul
