name: dmac_app
description: DMac AI Agent Swarm Flutter Application
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  flutter_markdown: ^0.6.15
  flutter_spinkit: ^5.2.0
  flutter_syntax_view: ^4.0.0
  # file_picker: ^6.1.1  # Commented out due to platform issues
  image_picker: ^0.8.7+5
  url_launcher: ^6.1.11

  # State Management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

  # Networking
  http: ^0.13.6
  dio: ^5.1.2
  web_socket_channel: ^2.4.0

  # Storage
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15

  # Authentication
  flutter_secure_storage: ^8.0.0

  # Utils
  intl: ^0.19.0
  logger: ^1.3.0
  uuid: ^3.0.7
  equatable: ^2.0.5
  json_annotation: ^4.8.1

  # Voice/Audio
  # permission_handler: ^10.2.0  # Commented out due to platform issues

  # Charts and Visualization
  fl_chart: ^0.62.0
  syncfusion_flutter_charts: ^21.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#6200EE"
  image: assets/images/splash_logo.png
  android: true
  ios: true
